### ISSUE TITLE
PRE-PR: structopt

### ISSUE THREAD

**Issue by XBagon** [ozankasikci/rust-music-theory#19]
I would like to rewrite the CLI part with [`structopt`](https://crates.io/crates/structopt), if you're fine with that. I think it would make the whole command & argument thing a lot easier to look at, understand and expand on.
Also I would like to resolve the panics occurring, when you're missing arguments, along with that.

(Independent from this specific Issue, I think it would make sense to have some kind of discussion platform for the further library design. I would like to contribute some more, but am very unsure if others would be fine with the changes or how I'd do them. And opening an issue for each possible feature I can think of seems a bit much. GitHub Discussions is still in Beta sadly..)

**Comment by ozankasikci** [comment]
Hi @XBagon, the CLI part can be improved, feel free if you want to do so! Resolving the panics would also be nice. But I'd like to add, I created CLI just to let people see the value of this project. The CLI has never been the goal, the goal was having a comprehensive GUI program that acts as a music theory Guide & Composition Helper, or even Composes music! I know it would be a huge undertaking to start working on something like that but just wanted to mention. Maybe we can implement that one day, maybe even using a pure Rust GUI library :)

Having an independent discussion platform makes sense! Let's evaluate the options for that 👍

**Comment by henryksloan** [comment]
@ozankasikci that's cool to know, I think this will be a great backend for a GUI. I've been using this library to make a counterpoint generation tool, and I recently added piano sounds using `rodio`. Maybe I'll work towards some components and features that would fit in well with an educational frontend for this library.

As far as CLI goes, I totally agree that panics should be eliminated where possible. I'm not experienced in clap or structopt, but I'm sure there's some good to be done.

**Comment by XBagon** [comment]
@ozankasikci Great, then I'll try my best to improve the CLI, on the GUI front I'm a lot less experienced and I'm not sure the ecosystem is ready yet 😅. But great to hear your plans, I'm planning to use it as a library (see below) and will try to improve and add stuff there, too.

For a discussion platform, the easiest is probably always Discord, so if you're down with that, that'd be cool.
Also if we really want to try out GitHub Discussions, I think you can just write to the Beta Team(?) and say you want to join, I've read you need at least 5 contributors, which seems to be the exact amount which this repo has at the moment 😄.

@henryksloan I had a very similar idea, I wanted to use the library for general procedural music generation and I already started building an "DAW"-crate https://gitlab.com/XBagon/dawrs (Will move it to GitHub if I'm somewhat happy with it), which I plan to expand a lot more in the next time.

**Comment by ozankasikci** [comment]
Unfortunately, that's true @XBagon. The ecosystem is not ready yet, moreover, it's going at a really slow pace. I already considered some Rust GUI libraries to start building a frontend, nothing seemed to be a good fit 😞 Otherwise I'd have already started the frontend project as well! Considered using Electron, QT or GTK,  but I really want to write it in Rust.

I applied for the Github Discussions Beta, we can give it a go.

I'm happy to hear about your plans guys, makes me believe that this project has nowhere near it's potential!

**Comment by XBagon** [comment]
Closed with #29
