### ISSUE TITLE
Need help with improving the documentation

### ISSUE THREAD

**Issue by ozankasikci** [ozankasikci/rust-music-theory#24]
The documentation is a bit outdated atm, after merging #20, the API will change dramatically and the gap will be even larger. We need to;

- Update that crate documentation
- Update the README file

If someone would like to pick that up please let the community know. Otherwise, I'll be working on that in the coming days.

**Comment by henryksloan** [comment]
Good call. I've been updating docstrings as I've made changes, so I think the docstrings pertaining to #20 should be good. In terms of the README and other docs, what exactly needs updating?

P.S. I think module files like like `src/notes.rs` should be moved to mod files like `src/notes/mod.rs`.

**Comment by ozankasikci** [comment]
Indeed, you've been updating the doc comments 👍 It seems the crate documentation is up to date but the latest version is not published on crates.io, that's something I will fix that issue quickly.

As for README, the example there is not valid anymore because the API has been changed for `Scale::new` and it's not valid atm. We definitely need to automate testing the examples in README as well.

We could use a crate like https://crates.io/crates/doc-comment or maybe some other, open to suggestions here!
