### ISSUE TITLE
Missing ♭ in accidental regex

### ISSUE THREAD

**Issue by martingronlund** [ozankasikci/rust-music-theory#3]
https://github.com/ozankasikci/rust-music-theory/blob/12983c2007195b5ca892057cf783545509df5d13/src/note/pitch_class.rs#L70

Could be nice when copy pasting, so I vouch to keep check and add in regex, instead of removing.

**Comment by ozankasikci** [comment]
@martingronlund that makes sense, could you please open a PR for this? Otherwise i will implement it.

**Comment by ozankasikci** [comment]
added [here](https://github.com/ozankasikci/rust-music-theory/commit/e0f78328109b6a4cedac28bb02e34eb3bbaf5b93), closing.
