### ISSUE TITLE
Running the scale command with any argument gives an error

### ISSUE THREAD

**Issue by amanharwara** [ozankasikci/rust-music-theory#30]
Command line output:

```
❯ rustmt scale D Locrian
error: Found argument 'D' which wasn't expected, or isn't valid in this context
USAGE:
    rustmt.exe scale <SUBCOMMAND>

For more information try --help
```

Same thing happens when using something like `rustmt scale C Minor`

Installed on a Windows 10 machine using `cargo install`.

**Comment by ozankasikci** [comment]
Hi @amanharwara, thanks for the reporting the issue!

I tried and indeed it gives an error. @XBagon this seems to be related to your latest PR regarding CLI refactoring, do you have an idea what is wrong here?

I will revert the changes for the being.

**Comment by ozankasikci** [comment]
@amanharwara reverted the CLI changes, if you pull the latest code, it should work now.

**Comment by amanharwara** [comment]
Works correctly now. Thanks!

**Comment by XBagon** [comment]
I really missed writing about this change. It's expecting the subcommand `notes` or `list`, `help` should clear this up.

I couldn't keep the current "API", cause `strucopt` doesn't allow it that easily, and I thought for good reason. The API would be a lot cleaner that way removing a parameter that can be a string argument **or** a subcommand. Really forgot to tell you about this or change the README, sorry!

I don't mind the reversion for the moment though, as I hadn't time to continue to work at it and add the missing features.
