### ISSUE TITLE
Dsus4 gives D-G-D

### ISSUE THREAD

**Issue by Psirus** [ozankasikci/rust-music-theory#31]
I was expecting this to output "DGA", but it outputs "DGD". But then I'm new to rust and basically cobbled together stuff from the tests I didn't understand. Where am I going wrong here?
~~~rust
extern crate rust_music_theory as rustmt;
use rustmt::note::Notes;
use rustmt::chord::Chord;

fn main() {
    let chord = Chord::from_regex("D sus4").unwrap();

    for note in chord.notes().iter() {
        print!("{}", note)
    }
}
~~~

**Comment by ReeceMcMillin** [comment]
Sus4 chords look to be represented as [0, 5, 7] intervals when it should be [0, 5, 2] (each interval is relative to the previous note, not the root). I'll go ahead and open a pull request with this changed and tests added to reflect. :)

**Comment by ozankasikci** [comment]
The issue should be resolved now.
