### ISSUE TITLE
Install option.

### ISSUE THREAD

**Issue by gorros** [ozankasikci/rust-music-theory#5]
I think it will be nice to mention that cli can be installed with cargo like this:
```
$ cargo install --git https://github.com/ozankasikci/rust-music-theory
```
and used as 
``` 
$ rmt scale D Locrian
```

However, there is old `rmt` Unix/Linux command,so maybe it is better to rename it.
But I've installed on Ubuntu in WSL and and it worked fine.

**Comment by ozankasikci** [comment]
Awesome suggestion. Going to rename the binary to rustmt, and add this instruction to the README, thanks!

**Comment by ozankasikci** [comment]
For the record, the binary is renamed from `rmt` to `rustmt`.
